# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 20:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='menu',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='tiles',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='tiles',
            name='ckeditor_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
