# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160909_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiles',
            name='pdf_path',
            field=models.CharField(default=datetime.datetime(2016, 9, 10, 11, 51, 42, 21000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
