# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20160910_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiles',
            name='pdf_path',
        ),
        migrations.AddField(
            model_name='tiles',
            name='pdf_path',
            field=models.ManyToManyField(to='menu.PDF'),
        ),
    ]
