# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-10 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20160910_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiles',
            old_name='pdf_path',
            new_name='pdf_files',
        ),
    ]
